/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'pnr' : string,
  'flight' : Flight,
  'passengers' : Array<Passenger>,
  'totalAmount' : bigint,
  'bookingTime' : bigint,
  'contactEmail' : string,
}
export interface Flight {
  'destination' : string,
  'arrivalTime' : bigint,
  'flightNumber' : string,
  'departureTime' : bigint,
  'origin' : string,
  'airline' : string,
  'price' : bigint,
  'classType' : FlightClass,
}
export type FlightClass = { 'economy' : null } |
  { 'business' : null };
export interface FlightSearchCriteria {
  'destination' : string,
  'date' : Time,
  'origin' : string,
  'passengers' : bigint,
  'classType' : FlightClass,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type PNR = string;
export interface Passenger {
  'age' : bigint,
  'name' : string,
  'email' : string,
  'gender' : Gender,
  'phone' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'createBooking' : ActorMethod<[string, Array<Passenger>, string], PNR>,
  'getBookingByPNR' : ActorMethod<[string], Booking>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getBookingsByEmail' : ActorMethod<[string], Array<Booking>>,
  'getFlights' : ActorMethod<[], Array<Flight>>,
  'searchFlights' : ActorMethod<[FlightSearchCriteria], Array<Flight>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];