/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Passenger = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'gender' : Gender,
  'phone' : IDL.Text,
});
export const PNR = IDL.Text;
export const FlightClass = IDL.Variant({
  'economy' : IDL.Null,
  'business' : IDL.Null,
});
export const Flight = IDL.Record({
  'destination' : IDL.Text,
  'arrivalTime' : IDL.Int,
  'flightNumber' : IDL.Text,
  'departureTime' : IDL.Int,
  'origin' : IDL.Text,
  'airline' : IDL.Text,
  'price' : IDL.Nat,
  'classType' : FlightClass,
});
export const Booking = IDL.Record({
  'pnr' : IDL.Text,
  'flight' : Flight,
  'passengers' : IDL.Vec(Passenger),
  'totalAmount' : IDL.Nat,
  'bookingTime' : IDL.Int,
  'contactEmail' : IDL.Text,
});
export const Time = IDL.Int;
export const FlightSearchCriteria = IDL.Record({
  'destination' : IDL.Text,
  'date' : Time,
  'origin' : IDL.Text,
  'passengers' : IDL.Nat,
  'classType' : FlightClass,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Vec(Passenger), IDL.Text],
      [PNR],
      [],
    ),
  'getBookingByPNR' : IDL.Func([IDL.Text], [Booking], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getFlights' : IDL.Func([], [IDL.Vec(Flight)], ['query']),
  'searchFlights' : IDL.Func(
      [FlightSearchCriteria],
      [IDL.Vec(Flight)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Passenger = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'gender' : Gender,
    'phone' : IDL.Text,
  });
  const PNR = IDL.Text;
  const FlightClass = IDL.Variant({
    'economy' : IDL.Null,
    'business' : IDL.Null,
  });
  const Flight = IDL.Record({
    'destination' : IDL.Text,
    'arrivalTime' : IDL.Int,
    'flightNumber' : IDL.Text,
    'departureTime' : IDL.Int,
    'origin' : IDL.Text,
    'airline' : IDL.Text,
    'price' : IDL.Nat,
    'classType' : FlightClass,
  });
  const Booking = IDL.Record({
    'pnr' : IDL.Text,
    'flight' : Flight,
    'passengers' : IDL.Vec(Passenger),
    'totalAmount' : IDL.Nat,
    'bookingTime' : IDL.Int,
    'contactEmail' : IDL.Text,
  });
  const Time = IDL.Int;
  const FlightSearchCriteria = IDL.Record({
    'destination' : IDL.Text,
    'date' : Time,
    'origin' : IDL.Text,
    'passengers' : IDL.Nat,
    'classType' : FlightClass,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Vec(Passenger), IDL.Text],
        [PNR],
        [],
      ),
    'getBookingByPNR' : IDL.Func([IDL.Text], [Booking], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getFlights' : IDL.Func([], [IDL.Vec(Flight)], ['query']),
    'searchFlights' : IDL.Func(
        [FlightSearchCriteria],
        [IDL.Vec(Flight)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };