/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Passenger {
    age: bigint;
    name: string;
    email: string;
    gender: Gender;
    phone: string;
}
export type Time = bigint;
export type PNR = string;
export interface Flight {
    destination: string;
    arrivalTime: bigint;
    flightNumber: string;
    departureTime: bigint;
    origin: string;
    airline: string;
    price: bigint;
    classType: FlightClass;
}
export interface Booking {
    pnr: string;
    flight: Flight;
    passengers: Array<Passenger>;
    totalAmount: bigint;
    bookingTime: bigint;
    contactEmail: string;
}
export interface FlightSearchCriteria {
    destination: string;
    date: Time;
    origin: string;
    passengers: bigint;
    classType: FlightClass;
}
export enum FlightClass {
    economy = "economy",
    business = "business"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export interface backendInterface {
    createBooking(flightNumber: string, passengers: Array<Passenger>, contactEmail: string): Promise<PNR>;
    getBookingByPNR(pnr: string): Promise<Booking>;
    getBookings(): Promise<Array<Booking>>;
    getBookingsByEmail(email: string): Promise<Array<Booking>>;
    getFlights(): Promise<Array<Flight>>;
    searchFlights(criteria: FlightSearchCriteria): Promise<Array<Flight>>;
}
import type { Booking as _Booking, Flight as _Flight, FlightClass as _FlightClass, FlightSearchCriteria as _FlightSearchCriteria, Gender as _Gender, Passenger as _Passenger, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createBooking(arg0: string, arg1: Array<Passenger>, arg2: string): Promise<PNR> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, to_candid_vec_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async getBookingByPNR(arg0: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingByPNR(arg0);
                return from_candid_Booking_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingByPNR(arg0);
            return from_candid_Booking_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByEmail(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByEmail(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByEmail(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlights(): Promise<Array<Flight>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlights();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlights();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchFlights(arg0: FlightSearchCriteria): Promise<Array<Flight>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFlights(to_candid_FlightSearchCriteria_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFlights(to_candid_FlightSearchCriteria_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Booking_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_FlightClass_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlightClass): FlightClass {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Flight_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Flight): Flight {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Passenger_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Passenger): Passenger {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    name: string;
    email: string;
    gender: _Gender;
    phone: string;
}): {
    age: bigint;
    name: string;
    email: string;
    gender: Gender;
    phone: string;
} {
    return {
        age: value.age,
        name: value.name,
        email: value.email,
        gender: from_candid_Gender_n15(_uploadFile, _downloadFile, value.gender),
        phone: value.phone
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pnr: string;
    flight: _Flight;
    passengers: Array<_Passenger>;
    totalAmount: bigint;
    bookingTime: bigint;
    contactEmail: string;
}): {
    pnr: string;
    flight: Flight;
    passengers: Array<Passenger>;
    totalAmount: bigint;
    bookingTime: bigint;
    contactEmail: string;
} {
    return {
        pnr: value.pnr,
        flight: from_candid_Flight_n8(_uploadFile, _downloadFile, value.flight),
        passengers: from_candid_vec_n12(_uploadFile, _downloadFile, value.passengers),
        totalAmount: value.totalAmount,
        bookingTime: value.bookingTime,
        contactEmail: value.contactEmail
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: string;
    arrivalTime: bigint;
    flightNumber: string;
    departureTime: bigint;
    origin: string;
    airline: string;
    price: bigint;
    classType: _FlightClass;
}): {
    destination: string;
    arrivalTime: bigint;
    flightNumber: string;
    departureTime: bigint;
    origin: string;
    airline: string;
    price: bigint;
    classType: FlightClass;
} {
    return {
        destination: value.destination,
        arrivalTime: value.arrivalTime,
        flightNumber: value.flightNumber,
        departureTime: value.departureTime,
        origin: value.origin,
        airline: value.airline,
        price: value.price,
        classType: from_candid_FlightClass_n10(_uploadFile, _downloadFile, value.classType)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    economy: null;
} | {
    business: null;
}): FlightClass {
    return "economy" in value ? FlightClass.economy : "business" in value ? FlightClass.business : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Passenger>): Array<Passenger> {
    return value.map((x)=>from_candid_Passenger_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Flight>): Array<Flight> {
    return value.map((x)=>from_candid_Flight_n8(_uploadFile, _downloadFile, x));
}
function to_candid_FlightClass_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlightClass): _FlightClass {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_FlightSearchCriteria_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlightSearchCriteria): _FlightSearchCriteria {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_Passenger_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Passenger): _Passenger {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: string;
    date: Time;
    origin: string;
    passengers: bigint;
    classType: FlightClass;
}): {
    destination: string;
    date: _Time;
    origin: string;
    passengers: bigint;
    classType: _FlightClass;
} {
    return {
        destination: value.destination,
        date: value.date,
        origin: value.origin,
        passengers: value.passengers,
        classType: to_candid_FlightClass_n21(_uploadFile, _downloadFile, value.classType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    name: string;
    email: string;
    gender: Gender;
    phone: string;
}): {
    age: bigint;
    name: string;
    email: string;
    gender: _Gender;
    phone: string;
} {
    return {
        age: value.age,
        name: value.name,
        email: value.email,
        gender: to_candid_Gender_n4(_uploadFile, _downloadFile, value.gender),
        phone: value.phone
    };
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlightClass): {
    economy: null;
} | {
    business: null;
} {
    return value == FlightClass.economy ? {
        economy: null
    } : value == FlightClass.business ? {
        business: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Passenger>): Array<_Passenger> {
    return value.map((x)=>to_candid_Passenger_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
